-- MySQL Script generated by MySQL Workbench
-- Thu Sep 12 11:54:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Little_Lemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Little_Lemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Little_Lemon` DEFAULT CHARACTER SET utf8 ;
USE `Little_Lemon` ;

-- -----------------------------------------------------
-- Table `Little_Lemon`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`Employees` (
  `idEmployeeID` INT NOT NULL,
  `EmployeeName` VARCHAR(255) NULL,
  `Role` VARCHAR(200) NULL,
  `Email` VARCHAR(255) NULL,
  PRIMARY KEY (`idEmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Little_Lemon`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`Customers` (
  `CustomerID` INT NOT NULL,
  `FullName` VARCHAR(50) NULL,
  `ContactNumber` INT NULL,
  `Email` VARCHAR(255) NULL,
  `Employees_idEmployeeID` INT NOT NULL,
  PRIMARY KEY (`CustomerID`),
  INDEX `fk_Customers_Employees1_idx` (`Employees_idEmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Employees1`
    FOREIGN KEY (`Employees_idEmployeeID`)
    REFERENCES `Little_Lemon`.`Employees` (`idEmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Little_Lemon`.`MenuItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`MenuItems` (
  `MenuItemID` INT NOT NULL,
  `CourseName` VARCHAR(200) NULL,
  `StarterName` VARCHAR(200) NULL,
  `DesertName` VARCHAR(200) NULL,
  PRIMARY KEY (`MenuItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Little_Lemon`.`Menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`Menus` (
  `MenuID` INT NOT NULL,
  `MenuName` VARCHAR(200) NULL,
  `Cuisine` VARCHAR(200) NULL,
  `MenuItems_MenuItemID` INT NOT NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `fk_Menus_MenuItems_idx` (`MenuItems_MenuItemID` ASC) VISIBLE,
  CONSTRAINT `fk_Menus_MenuItems`
    FOREIGN KEY (`MenuItems_MenuItemID`)
    REFERENCES `Little_Lemon`.`MenuItems` (`MenuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Little_Lemon`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`Delivery` (
  `DeliveryID` INT NOT NULL,
  `DeliveryDate` DATE NOT NULL,
  PRIMARY KEY (`DeliveryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Little_Lemon`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Little_Lemon`.`Orders` (
  `OrderID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Cost` DECIMAL(10,4) NOT NULL,
  `Customers_CustomerID` INT NOT NULL,
  `Menus_MenuID` INT NOT NULL,
  `Delivery_DeliveryID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_CustomerID` ASC) VISIBLE,
  INDEX `fk_Orders_Menus1_idx` (`Menus_MenuID` ASC) VISIBLE,
  INDEX `fk_Orders_Delivery1_idx` (`Delivery_DeliveryID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_CustomerID`)
    REFERENCES `Little_Lemon`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Menus1`
    FOREIGN KEY (`Menus_MenuID`)
    REFERENCES `Little_Lemon`.`Menus` (`MenuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Delivery1`
    FOREIGN KEY (`Delivery_DeliveryID`)
    REFERENCES `Little_Lemon`.`Delivery` (`DeliveryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
